name: CI/CD Pipeline

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-release:
    runs-on: self-hosted

    env:
      DOTNET_VERSION: '8.0.x'
      ASPNETCORE_ENVIRONMENT: 'Test' 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Restore dependencies
        run: dotnet restore ApiGateway.sln

      - name: Build solution
        run: dotnet build ApiGateway.sln --configuration Release --no-restore

      - name: Publish package
        run: dotnet publish ApiGateway.csproj --configuration Release --output ./publish

      - name: Archive package
        run: Compress-Archive -Path ./publish/* -DestinationPath ./ApiGateway.zip
        shell: powershell  

      - name: Create Release Version Tag
        id: tag
        run: |
          $version = "v1.0.0"
          echo "RELEASE_TAG=$version" >> $env:GITHUB_ENV
          echo "::set-output name=version::$version"
        shell: powershell

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          files: ApiGateway.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker image
        run: docker build -f ./Docker/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/apigateway-api:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/apigateway-api:latest 